### ISSUE TITLE
JVM args processing not working as expected

### ISSUE THREAD

**Issue by dpauly** [oracle/coherence-operator#364]
When I specify a default set of jvm args to be applied to all roles, as well as per-role jvm args, I get odd behaviour where the args are repeatedly added to the java command line.

See attached logs and cluster definition.
[log-excerpt.txt](https://github.com/oracle/coherence-operator/files/3822972/log-excerpt.txt)
[args.yaml.txt](https://github.com/oracle/coherence-operator/files/3822974/args.yaml.txt)

**Comment by thegridman** [comment]
This is now fixed and will be targeted for 2.0.1
