### ISSUE TITLE
On create cluster coherence and coherenceUtil Docker images not pulled from correct repo

### ISSUE THREAD

**Issue by sletov1** [oracle/coherence-operator#411]
On create cluster coherence and coherenceUtil Docker images not pulled from private repo.
Steps:

- pushed all required docker images to local/private repo
- created coher2 namespace 
- created secret
`kubectl create secret docker-registry xyzartifactory --docker-server=docker-xyz-virtual.artifactory.xyz.net --docker-username=user --docker-password=pwd --docker-email=sl@xyz.com -n coher2`
- Deployed successfully operator with overridden images 
`
helm install coherence/coherence-operator \
   --namespace coher2 \
   --set coherence.image=docker-xyz-virtual.artifactory.xyz.net/thirdparty/oracle/coherence:12.2.1.3.2 \
   --set coherenceUtils.image=docker-xyz-virtual.artifactory.xyz.net/thirdparty/oracle/coherence-operator:2.1.0-utils \
   --set coherenceOperator.image=docker-xyz-virtual.artifactory.xyz.net/thirdparty/oracle/coherence-operator:2.1.0 \
   --set imagePullSecrets[0].name=zxyzrtifactory \
   --generate-name 
` 
- Try to deploy simple cluster 
`
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: my-cluster
  namespace: coher2
spec:
  imagePullSecrets:
    - name: xyzartifactory
 `
- Error - ImagePullBackOff operator still tries to pull images from public hub

Images:
coherence               container-registry.oracle.com/middleware/coherence:12.2.1.4.0
coherence-k8s-utils     oracle/coherence-operator:2.1.0-utils

**Comment by aseovic** [comment]
@sletov1 Is this still relevant? Seems to be for an old, 2.x version of the operator, and I know we've changed the defaults in the meantime to pull public Coherence CE images from Docker Hub and GHCR, so I hope it is not an issue any more.
