### ISSUE TITLE
Does not work with helm 3

### ISSUE THREAD

**Issue by wenjian80** [oracle/coherence-operator#415]
Does not work with helm 3

**Comment by wenjian80** [comment]
[root@k8-coh-master coherence-operator]# helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
[root@k8-coh-master coherence-operator]# helm repo add coherence https://oracle.github.io/coherence-operator/charts
"coherence" has been added to your repositories
[root@k8-coh-master coherence-operator]# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "coherence" chart repository
Update Complete. ⎈ Happy Helming!⎈
[root@k8-coh-master coherence-operator]# helm install coherence-operator coherence/coherence-operator \
> --set prometheusoperator.enabled=true \
> --set prometheusoperator.prometheusOperator.createCustomResource=true \
> --set installEFK=true \
> --namespace coherence-example \
> --set imagePullSecrets[0].name=coherence-example-secret
load.go:112: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
load.go:112: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]

**Comment by thegridman** [comment]
Closing this because the latest Operator 3.0.0 version does work with Helm v3 and we have no intention of going back and changing v2.
