### ISSUE TITLE
Back-off restarting failed container

### ISSUE THREAD

**Issue by wenjian80** [oracle/coherence-operator#417]
Following the exampling in https://github.com/oracle/coherence-operator/tree/master/examples/deployment

kubectl -n coherence-example create -f example-cluster.yaml 

Container cannot be started

[root@k8-coh-master yaml]# kubectl describe po example-cluster-storage-0 -n coherence-example
Name:               example-cluster-storage-0
Namespace:          coherence-example
Priority:           0
PriorityClassName:  <none>
Node:               k8-coh-worker1/10.0.0.3
Start Time:         Fri, 12 Jun 2020 07:34:21 +0000
Labels:             coherenceCluster=example-cluster
                    coherenceDeployment=example-cluster-storage
                    coherenceRole=storage
                    coherenceWKAMember=true
                    component=coherencePod
                    controller-revision-hash=example-cluster-storage-9c644fd98
                    statefulset.kubernetes.io/pod-name=example-cluster-storage-0
Annotations:        <none>
Status:             Running
IP:                 10.244.1.46
Controlled By:      StatefulSet/example-cluster-storage
Init Containers:
  coherence-k8s-utils:
    Container ID:  docker://a9a4ba428fad1bf4bf8a2b4b15a484cb7d740974f8e2a31537d950854d398bef
    Image:         oracle/coherence-operator:2.1.1-utils
    Image ID:      docker-pullable://oracle/coherence-operator@sha256:9be64c88c81c8f58b1b08d1c7ee837e535224ac9652aee412b341824532019b0
    Port:          <none>
    Host Port:     <none>
    Command:
      /files/utils-init
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 12 Jun 2020 07:34:24 +0000
      Finished:     Fri, 12 Jun 2020 07:34:24 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      COH_UTIL_DIR:      /utils
      COH_CLUSTER_NAME:  example-cluster
    Mounts:
      /utils from utils-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hdt6s (ro)
  application:
    Container ID:  docker://7c296704033e4a4ebcdaf4f3d8ba5d42d73efc88cac26e218d288f80bd38cdb6
    Image:         bjlim80/deployment-example:2.1.2
    Image ID:      docker-pullable://bjlim80/deployment-example@sha256:50438249f7f1575435292294fce5d52412bce056e28796d1712f19609856d296
    Port:          <none>
    Host Port:     <none>
    Command:
      /utils/copy
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 12 Jun 2020 07:34:25 +0000
      Finished:     Fri, 12 Jun 2020 07:34:25 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      EXTERNAL_APP_DIR:   /u01/oracle/oracle_home/coherence/app
      APP_DIR:            /app
      EXTERNAL_LIB_DIR:   /u01/oracle/oracle_home/coherence/app/lib
      LIB_DIR:            /app/lib
      EXTERNAL_CONF_DIR:  /u01/oracle/oracle_home/coherence/app/conf
      CONF_DIR:           /app/conf
    Mounts:
      /u01/oracle/oracle_home/coherence/app from application-dir (rw)
      /utils from utils-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hdt6s (ro)
Containers:
  coherence:
    Container ID:  docker://4137eb06fee19b8903fc2ea22fa512e39c58279836a9b8a7dcc02b3b468066e4
    Image:         fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3
    Image ID:      docker-pullable://fluent/fluentd-kubernetes-daemonset@sha256:f7fa2c03cef32ed05d169930bcf0f8f44380f47dcf59470094f459a8f7995c84
    Ports:         7/TCP, 6676/TCP, 9612/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -x
      /scripts/startCoherence.sh
      server
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 12 Jun 2020 07:40:20 +0000
      Finished:     Fri, 12 Jun 2020 07:40:20 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:  32
    Requests:
      cpu:      0
    Liveness:   http-get http://:6676/healthz delay=45s timeout=5s period=60s #success=1 #failure=5
    Readiness:  http-get http://:6676/ready delay=30s timeout=5s period=60s #success=1 #failure=50
    Environment:
      COH_WKA:                   example-cluster-wka
      COH_APP_DIR:               /u01/oracle/oracle_home/coherence/app
      COH_EXTRA_CLASSPATH:       /u01/oracle/oracle_home/coherence/app/lib/*:/u01/oracle/oracle_home/coherence/app/conf
      COH_MGMT_HTTP_PORT:        30000
      COH_METRICS_PORT:          9612
      COH_MACHINE_NAME:           (v1:spec.nodeName)
      COH_MEMBER_NAME:           example-cluster-storage-0 (v1:metadata.name)
      COH_POD_UID:                (v1:metadata.uid)
      OPERATOR_HOST:             <set to the key 'operatorhost' in secret 'coherence-operator-config'>  Optional: true
      COH_SITE_INFO_LOCATION:    http://$(OPERATOR_HOST)/site/$(COH_MACHINE_NAME)
      COH_RACK_INFO_LOCATION:    http://$(OPERATOR_HOST)/rack/$(COH_MACHINE_NAME)
      COH_CLUSTER_NAME:          example-cluster
      COH_ROLE:                  storage
      COH_UTIL_DIR:              /utils
      JVM_USE_CONTAINER_LIMITS:  true
      JVM_FLIGHT_RECORDER:       true
      JVM_HEAP_SIZE:             512m
      JVM_GC_LOGGING:            true
      COH_CACHE_CONFIG:          storage-cache-config.xml
      OPERATOR_REQUEST_TIMEOUT:  120
      COH_MGMT_ENABLED:          false
      COH_METRICS_ENABLED:       true
      COH_HEALTH_PORT:           6676
      COH_LOGGING_CONFIG:        /scripts/logging.properties
    Mounts:
      /jvm from jvm (rw)
      /logs from log-dir (rw)
      /scripts from coherence-scripts (rw)
      /u01/oracle/oracle_home/coherence/app from application-dir (rw)
      /utils from utils-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hdt6s (ro)
  fluentd:
    Container ID:  docker://4663b514b2c3b2ed0333c8013349b45dd007834dbd4253c051c9ba31cdffc7ba
    Image:         fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3
    Image ID:      docker-pullable://fluent/fluentd-kubernetes-daemonset@sha256:f7fa2c03cef32ed05d169930bcf0f8f44380f47dcf59470094f459a8f7995c84
    Port:          <none>
    Host Port:     <none>
    Args:
      -c
      /etc/fluent.conf
    State:          Running
      Started:      Fri, 12 Jun 2020 07:34:30 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      COHERENCE_POD_ID:                   (v1:metadata.uid)
      FLUENTD_CONF:                      fluentd-coherence.conf
      FLUENT_ELASTICSEARCH_SED_DISABLE:  true
      ELASTICSEARCH_USER:                <set to the key 'elasticsearchuser' in secret 'coherence-monitoring-config'>      Optional: true
      ELASTICSEARCH_PASSWORD:            <set to the key 'elasticsearchpassword' in secret 'coherence-monitoring-config'>  Optional: true
      ELASTICSEARCH_HOSTS:               <set to the key 'elasticsearchhosts' in secret 'coherence-monitoring-config'>     Optional: true
      ELASTICSEARCH_SCHEME:              <set to the key 'elasticsearchscheme' in secret 'coherence-monitoring-config'>    Optional: true
    Mounts:
      /fluentd/etc/fluentd-coherence.conf from fluentd-coherence-conf (rw)
      /logs from log-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hdt6s (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  log-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  utils-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  application-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  jvm:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  coherence-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      example-cluster-storage-scripts
    Optional:  false
  fluentd-coherence-conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      example-cluster-storage-efk-config
    Optional:  false
  default-token-hdt6s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hdt6s
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                     Message
  ----     ------     ----                   ----                     -------
  Normal   Scheduled  6m31s                  default-scheduler        Successfully assigned coherence-example/example-cluster-storage-0 to k8-coh-worker1
  Normal   Created    6m29s                  kubelet, k8-coh-worker1  Created container
  Normal   Pulled     6m29s                  kubelet, k8-coh-worker1  Container image "oracle/coherence-operator:2.1.1-utils" already present on machine
  Normal   Started    6m28s                  kubelet, k8-coh-worker1  Started container
  Normal   Pulled     6m28s                  kubelet, k8-coh-worker1  Container image "bjlim80/deployment-example:2.1.2" already present on machine
  Normal   Created    6m28s                  kubelet, k8-coh-worker1  Created container
  Normal   Started    6m27s                  kubelet, k8-coh-worker1  Started container
  Normal   Pulled     6m22s                  kubelet, k8-coh-worker1  Container image "fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3" already present on machine
  Normal   Created    6m22s                  kubelet, k8-coh-worker1  Created container
  Normal   Started    6m22s                  kubelet, k8-coh-worker1  Started container
  Normal   Pulled     5m34s (x4 over 6m23s)  kubelet, k8-coh-worker1  Container image "fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3" already present on machine
  Normal   Created    5m34s (x4 over 6m23s)  kubelet, k8-coh-worker1  Created container
  Normal   Started    5m33s (x4 over 6m22s)  kubelet, k8-coh-worker1  Started container
  Warning  BackOff    86s (x25 over 6m16s)   kubelet, k8-coh-worker1  Back-off restarting failed container

**Comment by thegridman** [comment]
This is a bug in Operator v2.1.1. As there is a work around and this has been superseded by Operator v3.0.0 we're not fixing it.

The specific scenario is deploying a `CoherenceCluster` that does not specify a Coherence image name and enables Fluentd logging.
For example:

```
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  logging:
    fluentd:
      enabled: true
```

For some reason we have yet to figure out the `StatefulSet` is deployed correctly then immediately updated with an invalid configuration.
The work around is that if `logging.fluentd.enabled` is set to `true` then always set the `coherence.image` too.
For example:
```
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    image: container-registry.oracle.com/middleware/coherence:14.1.1.0.0
  logging:
    fluentd:
      enabled: true
```
