### ISSUE TITLE
demo does not build

### ISSUE THREAD

**Issue by ngkmh** [oracle/coherence-operator#436]
When I try to build demo, I get an error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Oracle Coherence Operator Examples Parent 3.0.2:
[INFO] 
[INFO] Oracle Coherence Operator Examples Parent .......... SUCCESS [  0.814 s]
[INFO] Coherence Operator Deployment Example .............. FAILURE [  5.257 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.202 s
[INFO] Finished at: 2020-08-06T15:41:38+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project deployment-example: Fatal error compiling: invalid flag: --release -> [Help 1]

Removing the release parameter for that plugin fixed it

**Comment by tmiddlet2666** [comment]
Fixed in https://github.com/oracle/coherence-operator/commit/4fefbe6a75996a404083380b52ad26c16fe16104
