### ISSUE TITLE
Steps to update Coherence operator to 3.1.0 from 3.0.2

### ISSUE THREAD

**Issue by viju2008** [oracle/coherence-operator#458]
I am unable to upgrade or update the coherence operator from 3.0.2 to 3.1.0

I have two namespaces coherence-example and coherence-demo-ns

Coherence-example has 3.0.2.

I tried helm upgrade and helm update .. helm delete..

But helm install again pulls up 3.0.2

**Comment by viju2008** [comment]
ubuntu@acsokecluster2:~$ helm --debug install coherence/coherence-operator  --set "targetNamespaces={coherence-demo-ns}"   --version 3.1.1 --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/config
install.go:172: [debug] Original chart version: "3.1.1"
Error: chart "coherence-operator" matching 3.1.1 not found in coherence index. (try 'helm repo update'): no chart version found for coherence-operator-3.1.1
helm.go:94: [debug] no chart version found for coherence-operator-3.1.1
helm.sh/helm/v3/pkg/repo.IndexFile.Get
        /home/circleci/helm.sh/helm/pkg/repo/index.go:193
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:232
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:669
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:184
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
chart "coherence-operator" matching 3.1.1 not found in coherence index. (try 'helm repo update')
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:234
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:669
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:184
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by viju2008** [comment]
ubuntu@acsokecluster2:~$ helm --debug install coherence/coherence-operator  --set "targetNamespaces={coherence-demo-ns}"   --version 3.1.0 --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/config
install.go:172: [debug] Original chart version: "3.1.0"
Error: chart "coherence-operator" matching 3.1.0 not found in coherence index. (try 'helm repo update'): no chart version found for coherence-operator-3.1.0
helm.go:94: [debug] no chart version found for coherence-operator-3.1.0
helm.sh/helm/v3/pkg/repo.IndexFile.Get
        /home/circleci/helm.sh/helm/pkg/repo/index.go:193
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:232
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:669
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:184
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
chart "coherence-operator" matching 3.1.0 not found in coherence index. (try 'helm repo update')
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:234
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:669
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:184
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
ubuntu@acsokecluster2:~$

**Comment by viju2008** [comment]
ubuntu@acsokecluster2:~$ helm --debug install coherence/coherence-operator  --set "targetNamespaces={coherence-demo-ns}"   --version 3.1.0 --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/config
install.go:172: [debug] Original chart version: "3.1.0"
Error: chart "coherence-operator" matching 3.1.0 not found in coherence index. (try 'helm repo update'): no chart version found for coherence-operator-3.1.0
helm.go:94: [debug] no chart version found for coherence-operator-3.1.0

**Comment by viju2008** [comment]
ubuntu@acsokecluster2:~$ helm --debug install coherence/coherence-operator  --set "targetNamespaces={coherence-demo-ns}"   --version 3.1.1 --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/config
install.go:172: [debug] Original chart version: "3.1.1"
Error: chart "coherence-operator" matching 3.1.1 not found in coherence index. (try 'helm repo update'): no chart version found for coherence-operator-3.1.1
helm.go:94: [debug] no chart version found for coherence-operator-3.1.1

**Comment by thegridman** [comment]
The release process for 3.1.0 had not released the Helm chart. This has been fixed now.
