### ISSUE TITLE
Operator deployment yaml files

### ISSUE THREAD

**Issue by viju2008** [oracle/coherence-operator#459]
Hello 

Please provide us yaml files to install the coherence operator on -premise.

We cannot access the operator images from external sources directly like oracle.github.io or helm hub.

We will get the docker images on local for coherence-operator and its utils image.

I tried using the old yaml file but it didnt work

**Comment by thegridman** [comment]
https://oracle.github.io/coherence-operator/docs/3.1.1/#/installation/01_installation#kubectl
