### ISSUE TITLE
Spelling Error in Coherence Cache Details Dashboard Panel

### ISSUE THREAD

**Issue by jburgess** [oracle/coherence-operator#486]
There is a spelling mistake on the dashboard panel `Cache Storage Details for Cache $CacheName` for column 'Non `Opttimzed` Query Time'

https://github.com/oracle/coherence-operator/blob/45fbaeb816b94a6b62962acb98d245a01fea3dfb/dashboards/grafana/cache-details-dashboard.json#L1336

**Comment by tmiddlet2666** [comment]
Thanks @jburgess

**Comment by thegridman** [comment]
Merged in #487
