### ISSUE TITLE
Unable to use RollingUpdate strategy

### ISSUE THREAD

**Issue by a-t-u-l-k** [oracle/coherence-operator#602]
We're trying to use RollingUpdate Strategy with Coherence CRD
`
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
`
But seems like it is not supported:
` [helm] WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /secret/kubeconfig/.kubeconfig   
[helm] Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Coherence.spec): unknown field "strategy" in com.oracle.coherence.v1.Coherence.spec   
okecluster_helm_release.helm["omni-data-plane-svc-chat-chart-us-ashburn-1"]: Still modifying... [id=omni-data-plane-svc-chat-chart-us-ashbu...w5q4qceelqio5fs2lshyp7bndixcfavekz2oyq, 30s elapsed]   
okecluster_helm_release.helm["omni-data-plane-svc-chat-chart-us-ashburn-1"]: Still modifying... [id=omni-data-plane-svc-chat-chart-us-ashbu...w5q4qceelqio5fs2lshyp7bndixcfavekz2oyq, 40s elapsed]   
   `

**Comment by thegridman** [comment]
Hi,

This was answered on Slack. It is better to only ask questions in one place as it causes a lot of noise by asking the same thing in multiple places and it does not guarantee you get an answer any quicker.
<https://corparch-core-srv.slack.com/archives/CHPGHDLN7/p1687850610216129>
Sign in to Oracle<https://corparch-core-srv.slack.com/archives/CHPGHDLN7/p1687850610216129>
corparch-core-srv.slack.com<https://corparch-core-srv.slack.com/archives/CHPGHDLN7/p1687850610216129>
[favicon-32-ua.png]<https://corparch-core-srv.slack.com/archives/CHPGHDLN7/p1687850610216129>


On 27 Jun 2023, at 10:20, Atul Kumar ***@***.***> wrote:



We're trying to use RollingUpdate Strategy with Coherence CRD
spec: strategy: type: RollingUpdate rollingUpdate: maxSurge: 3 maxUnavailable: 0
But seems like it is not supported:
`[helm] WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /secret/kubeconfig/.kubeconfig
[helm] Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Coherence.spec): unknown field "strategy" in com.oracle.coherence.v1.Coherence.spec
okecluster_helm_release.helm["omni-data-plane-svc-chat-chart-us-ashburn-1"]: Still modifying... [id=omni-data-plane-svc-chat-chart-us-ashbu...w5q4qceelqio5fs2lshyp7bndixcfavekz2oyq, 30s elapsed]
okecluster_helm_release.helm["omni-data-plane-svc-chat-chart-us-ashburn-1"]: Still modifying... [id=omni-data-plane-svc-chat-chart-us-ashbu...w5q4qceelqio5fs2lshyp7bndixcfavekz2oyq, 40s elapsed]

Error: Unexpected Error
Service: Okeclusters
Error Message: helm command ["helm" "upgrade" "omni-data-plane-svc-chat-chart-us-ashburn-1" "/secret/chart/chart.tgz" "--install" "--create-namespace" "--wait" "--history-max" "0" "--namespace" "chat" "--render-subchart-notes" "--timeout" "300s" "--values" "/secret/values/values.yaml"] failed with exit code: 1

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /secret/kubeconfig/.kubeconfig
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Coherence.spec): unknown field "strategy" in com.oracle.coherence.v1.Coherence.spec `

**Comment by a-t-u-l-k** [comment]
Apologies, I created the issue first, wasn't sure whether this is being monitored, so, pinged the same over slack. I understand your pain of answering at multiple places, will take care of this in the future posts.

Thanks for your explanation, closing this.
