### ISSUE TITLE
user guide doc on how to scrape coherence server members with external prometheus server

### ISSUE THREAD

**Issue by jfialli** [oracle/coherence-operator#77]
Requirements:
- Describe how to discover coherence cache server members endpoint 
  without relying on the cohernece-operator subchart prometheusoperator.enabled set to true.

- Prerequisites for coherence versions required.

- Troubleshooting section for when failing to scrape coherence metrics.

**Comment by tmiddlet2666** [comment]
@jfialli we should include these instructions in the sample here - https://github.com/oracle/coherence-operator/tree/issue-77-support-for-external-prometheus-server/docs/samples/operator/metrics/own-prometheus

**Comment by tmiddlet2666** [comment]
https://github.com/oracle/coherence-operator/pull/199
